services:
  - type: web
    name: brasilburger-mvc
    runtime: dotnet
    plan: free
    rootDirectory: BrasilburgerC  # IMPORTANT : indique le sous-dossier
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: cd ./publish && dotnet BrasilburgerC.dll --urls=http://0.0.0.0:$PORT
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    autoDeploy: true