services:
  - type: web
    name: monappmvc
    env: docker
    region: frankfurt
    plan: free
    branch: feature/csharp-mvc  # Remplacez par VOTRE nom de branche
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production